### ISSUE TITLE
zsh or bash? [edit: zsh fork desired]

### ISSUE THREAD

**Issue by anthonybrown** [jeremybradbury/mac-php-dev-env#1]
Not really an issue just a quick question, does it matter what shell I'm using? I prefer the zsh shell over the bash shell

**Comment by jeremybradbury** [comment]
It was written for out of the box Yosemite Terminal, so I would say bash (even though technically I believe it’s a posix based bash clone?). Not a lot of testing has been done, but all the scripts (except lamp.sh which was based on a tutorial and has link) are quite simple scripts that I tried to comment/console.out clearly.

If you know both bash and zsh reading them is where I would start (I think very minor changes are needed). Then feel free to fork it and make a zsh copy for yourself, and maybe change some of the browsers/IDEs/editors in cask.sh. If you do make a straight copy of a zsh (before you fork again and customize), let me know and I will link to it from the main repo.

Just a note, for everyone:

This wasn’t really designed as setup for beginners, more like a time saver for experts. The script’s scope is: _'to restore a working developer machine from a fresh install and some backups in the most unattended way'._ There are tons of similar scripts and gists on github since caskroom.io cropped up. The best plan is to have something like this forked on your own github (that can’t be changed by others without a PR).

It also needs improvements and optimizations. However, If the Pull Requests fall outside of the original scope I won’t accept them. Like before when I (yes I broke the rules) added checks for if you were sure as each thing installed (we need to be unattended as best as possible) or when I tried to detect if something was installed first (this should be wiped or at very least had homebrew wiped and /usr/local rolled back the homebrew way).

Thanks for stopping by! I <3 contributors. =D

**Comment by anthonybrown** [comment]
So this is for experts only, I am not an expert in Bash script nor PHP
I'm going to figure this out though, thanks for your help +!

**Comment by jeremybradbury** [comment]
I love your attitude! I am the same way. I didn’t mean to discourage you, just give some perspective as to why this isn’t better supported or simpler to understand. I pretty much just took a couple days of work to get this done so that setting up my loaner wouldn’t be too discouraging (because it will be replaced soon and I’ll need to provision a replacement shortly after) AND to give my teammates a helpful tool.

That said, if you can make it work: USE IT. Lamp.sh saves me tons of time just using the Auto Virtual Hosts (it even supports symlinks which is vital for working with repos that don’t have their webroot at the repo’s top level). The rest of the script had me up and running in about 2 hours and does it consistently. I don’t have to remember what apps I installed or in what order, the script remembers. And keeping my /Users/jeremy folder on a Time Machine backup means that I don't have to lose my app preferences either.

The notes below are mostly for other readers, but feel free to check out these resources.

If you are just playing around or wanting EASIER setup of a LAMP stack I recommend this VM: http://laravel.com/docs/4.2/homestead which isn’t just good for Laravel projects (and is well supported), and supports HHVM (the Facebook built fast php mulit-threading engine).

For even more Mac brainlessness: there is MAMP which is simple enough for most people and gets the job done OR XAMPP (I highly recommend) which is a multi-platform, easy to configure multiple PHP versions, mature, fully featured LAMP-in-a-box: https://www.apachefriends.org
